### ISSUE TITLE
Alternate ports not working

### ISSUE THREAD

**Issue by tpitman** [heroiclabs/nakama-docs#100]
I have nakama running on my mac. Everything is the latest that I just installed over the last few days.

When I try to change the port to anything other than the default by using the config file I can't connect to it.

I just get a connection refused.

In my config file I have this:

console:
  port: 7288
  username: myuser
  password: mypass

When I run docker the output says:

`nakama         | {"level":"info","ts":"2019-05-20T16:05:39.037Z","msg":"Starting Console server for gRPC requests","port":7285}
nakama         | {"level":"info","ts":"2019-05-20T16:05:39.037Z","msg":"Starting Console server gateway for HTTP requests","port":7288}
nakama         | {"level":"info","ts":"2019-05-20T16:05:39.038Z","msg":"Starting API server for gRPC requests","port":7349}
nakama         | {"level":"info","ts":"2019-05-20T16:05:39.038Z","msg":"Starting API server gateway for HTTP requests","port":7350}
nakama         | {"level":"info","ts":"2019-05-20T16:05:39.521Z","msg":"Startup done"}`

If I then browse to localhost:7288 it says connection refused.

If I take out the port: 7288 from the config and run it I get this:

`nakama         | {"level":"info","ts":"2019-05-20T16:06:51.991Z","msg":"Starting Console server for gRPC requests","port":7348}
nakama         | {"level":"info","ts":"2019-05-20T16:06:51.992Z","msg":"Starting Console server gateway for HTTP requests","port":7351}
nakama         | {"level":"info","ts":"2019-05-20T16:06:51.992Z","msg":"Starting API server for gRPC requests","port":7349}
nakama         | {"level":"info","ts":"2019-05-20T16:06:51.992Z","msg":"Starting API server gateway for HTTP requests","port":7350}
nakama         | {"level":"info","ts":"2019-05-20T16:06:52.494Z","msg":"Startup done"}`

If I then browse to localhost:7351 everything works fine.

What do I do to change the port and have it work?

**Comment by novabyte** [comment]
@tpitman Do you use Docker compose to run the server? If so have you exposed the new port you want to use outside of Docker engine?

**Comment by tpitman** [comment]
Thank you. That must be it. I didn't change any of the ports in the docker compose file.

**Comment by novabyte** [comment]
No worries. Happy to help @tpitman let me know if the problem persists and re-open this issue.
