### ISSUE TITLE
Unclear stackdriver metrics project Id

### ISSUE THREAD

**Issue by bran-san** [heroiclabs/nakama-docs#113]
This is applicable for the projects which are not managed by people themselves.

It is not clear if the project Id the configuration requires is the id of project managed by heroiclabs or the project Id to which we may want to send it to (which might be the case if the client has their own GCP project).

**Comment by seanpackham** [comment]
We've recently update the configuration docs with more info on varius options, hope that helps https://heroiclabs.com/docs/nakama/getting-started/configuration/#metrics
