### ISSUE TITLE
Godot snippets link leads to a 404

### ISSUE THREAD

**Issue by NathanLovato** [heroiclabs/nakama-docs#123]
The Nakama Godot  docs link to a non-existing page with code snippets, http://github.com/heroiclabs/nakama-godot/tree/master/snippets.

The link is at the bottom of this page: https://heroiclabs.com/docs/godot-client-guide/

I looked around your github organization and couldn't find the snippets in question. Do you have them available somewhere?

**Comment by seanpackham** [comment]
Thanks Nathan the broken link has been fixed a while back so I'll close this issue.
