### ISSUE TITLE
.NET/Unity have to be separated

### ISSUE THREAD

**Issue by Nembrot** [heroiclabs/nakama-docs#124]
at least Socket part of documentation pertains only to Unity as the client.NewSocket resides in ClientExtensions in Unity code only.

**Comment by seanpackham** [comment]
@lugehorsam is this still the case, do we have a .NET equivalent with no Unity dependency? I guess this is sort of linked to testing the client library in Godot C# too.

**Comment by lugehorsam** [comment]
@seanpackham yes we have a `.NET` core that is a separate library pulled into the `Unity` library.

Someone from the community tested C# and Godot and it worked 👍

**Comment by lugehorsam** [comment]
Wait @seanpackham this issue is separate from anything related to Godot. It sounds like he's saying our docs only cover the Unity approach and not the .NET approach.

**Comment by seanpackham** [comment]
Thanks @lugehorsam what would the .NET equivalent be, could you point me to a reference and I'll update our docs.

**Comment by lugehorsam** [comment]
Well he's saying this whole section: https://heroiclabs.com/docs/nakama/client-libraries/unity-client-guide/ needs to be split out into .NET so there's no single reference to update. 

In general these are the best places to look for the pure .NET stuff:

https://github.com/heroiclabs/nakama-dotnet/tree/master/tests/Nakama.Tests
https://github.com/heroiclabs/nakama-dotnet/tree/master/examples/Nakama.Examples

**Comment by seanpackham** [comment]
Thank you Luke, yes we will add a new client guide and also update various snippets elsewhere in the docs that use the Unity specific code.

**Comment by seanpackham** [comment]
We're tracking this task in our internal project management.

**Comment by mofirouz** [comment]
Documentation has been updated on this. Closing this issue for now.
