### ISSUE TITLE
Changing the language of 1 code block should update the entire page

### ISSUE THREAD

**Issue by Nikola-Milovic** [heroiclabs/nakama-docs#129]
Just a slight quality of life, when you go to a page in the docs and select a language (C++ for example), all the other code blocks should be C++. Idk what else to say about this, just  go here https://developer.android.com/training/dependency-injection?hl=nl#java and click a box to change to kotlin and the entire page will be updated.

**Comment by seanpackham** [comment]
Thank you Nikola we are adding a site wide language changed to the new documentation platform we are working on.
