### ISSUE TITLE
Document the Developer Console found within Nakama

### ISSUE THREAD

**Issue by AlimJaffer** [heroiclabs/nakama-docs#133]
Many developers are unaware of the fact that we have bundled the Developer Console into Nakama which is available for them to access locally via port 7351.  

Further details on the Developer Console can be found in our announcement blog post: https://blog.heroiclabs.com/the-nakama-developer-console-2b7e74ca43b4

**Comment by gpene** [comment]
See: https://heroiclabs.com/docs/console-overview/
