### ISSUE TITLE
Lua client guide missing?

### ISSUE THREAD

**Issue by subsoap** [heroiclabs/nakama-docs#136]
https://heroiclabs.com/docs/lua-client-guide should this work?

**Comment by novabyte** [comment]
@subsoap Sorry the docs deployment hasn't refreshed across our CDN yet I think.

**Comment by seanpackham** [comment]
Hi subsoap that latest Lua client guide can be found here https://heroiclabs.com/docs/nakama/client-libraries/defold-client-guide/ we are also working on refreshing all our clients guides with more examples.
