### ISSUE TITLE
In-app Notification wrong example.

### ISSUE THREAD

**Issue by ChimpSay** [heroiclabs/nakama-docs#137]
https://heroiclabs.com/docs/runtime-code-function-reference/#notifications

![image](https://user-images.githubusercontent.com/61688860/83139876-5ca17580-a0ed-11ea-9ebe-1cb0bb4745e9.png)

Example shows that you should call `nk.json_encode(content)` but that would result in an error.

**Comment by gpene** [comment]
Example has been updated.
