### ISSUE TITLE
Either update repository to support latest mkdocs-material version (5.x) or specify pre-5.x material pip installation

### ISSUE THREAD

**Issue by lugehorsam** [heroiclabs/nakama-docs#146]
The current installation instructions result in an error when running `mkdocs serve` because of a breaking change to a recent version of mkdocs-material.

Specifically, I received this exception: `jinja2.exceptions.TemplateNotFound: .icons/.svg`

This is due to this 4.x -> 5.x breaking change:
https://squidfunk.github.io/mkdocs-material/releases/5/#extrasocial

I was able to successfully serve the docs using `mkdocs-material-4.6.3`.

**Comment by lugehorsam** [comment]
Let me know which approach we'd like to take (I'd assume simply updating to 5.x) and I can go ahead and do that.

**Comment by novabyte** [comment]
Hey @lugehorsam. I think we should definitely update to the latest release of mkdocs and also the latest release of mkdocs-material if it has some kind of semi-official or improved support for code tabs. Would be great if you could tackle it 🙏
