### ISSUE TITLE
Info on how to use Nakama with headless Unity/Unreal/GenericGameEngine

### ISSUE THREAD

**Issue by asheraryam** [heroiclabs/nakama-docs#161]
Using Nakama plus a headless engine instance is a very attractive scenario for professional projects, and there's a significant amount of demand for this in FPS/Moba/Action game discussions, basically anything on the other end of the precision/performance scale of networking requirements.

Off the top of my head, the docs should help explain how the Auth workflow would work, I remember asking a while ago and hearing it'll involve passing session tokens around, but that doesn't help get one very far if they have game engine knowledge > web dev knowledge.

Also best practices for other features like realtime chatting (I am guessing clients would send chat messages to Nakama directly instead of the headless server? Would be nice to confirm that).

Additionally, might be worth talking about matchmaking and spawning additional headless instances.

**Comment by seanpackham** [comment]
Hi @asheraryam the setup will depend on the specific engine and features you are using. Most people with similar use cases tend to use Nakama's social and competitive features and the engine for game networking. You will need to share your match IDs with your game server and trigger events between the two by call RPCs. Take a look at our documentation for defining and calling RPC from various engines or over HTTP https://heroiclabs.com/docs/nakama/server-framework/basics/#register-hooks

There is also a community guide to do something similar with Nakama and WebRTC https://www.snopekgames.com/tutorial/2021/how-use-webrtc-godot-nakama-signalling-server
