### ISSUE TITLE
How can I use 'Stream Presence' ?

### ISSUE THREAD

**Issue by chounry** [heroiclabs/nakama-docs#166]
I see the document talking about it, there are Lua and Go script code. Do I need to put it in the nakama server?

If that so, where should I put it, and how can I call it on client?

**Comment by novabyte** [comment]
@chounry Did you work this out? You should have a read of this part of our docs:

https://heroiclabs.com/docs/runtime-code-basics/

**Comment by chounry** [comment]
Yes, I have manage to do after read the doc again. Thanks you

**Comment by chounry** [comment]
But I have another question which is how can we create a lobby with specific amount of participant? I meant like gathering other player as a team or play as a team.

**Comment by novabyte** [comment]
@chounry I think for follow up questions its best you join the forums and ask the question there. This issue tracker is not the best place to converse unless its about an error or typo in the documentation. - [https://forum.heroiclabs.com/](https://forum.heroiclabs.com/)
