### ISSUE TITLE
Broken link at `TypeScript Setup`

### ISSUE THREAD

**Issue by galkin** [heroiclabs/nakama-docs#183]
@novabyte,

At [runtime-code-typescript-setup](https://github.com/heroiclabs/nakama-docs/blob/master/docs/runtime-code-typescript-setup.md) link to `Nakama project template` is broken. I guess the project is private, not public. Could you fix it?

PS Happy New Year! 🥳

**Comment by novabyte** [comment]
Nice catch @galkin. The docs deployed ahead of the final improvements we have for the TypeScript support. I'll make a note to sort it when we're back next week. Happy New Year to you as well! 🥳

**Comment by galkin** [comment]
@novabyte, i will be happy to be typescript alpha tester.

**Comment by novabyte** [comment]
@galkin That would be great! Please send me a DM over Gitter and we can sort out how you can experiment with the release. :)

**Comment by novabyte** [comment]
This was resolved when the Nakama project template was made public:

https://github.com/heroiclabs/nakama-project-template
