### ISSUE TITLE
Cocos Creator (JS) code examples are outdated.

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama-docs#197]
The improvements to the TypeScript/JavaScript client which added convenience methods for the client and socket object types in the SDK are reused in the nakama-cocos2d-x-javascript client. We should update those code examples in the docs to match the JS code examples.

**Comment by lugehorsam** [comment]
@novabyte I actually had updated the docs for cocos-2d-js when I added those convenience methods. The issue was there was no official release for that client. Just pushed a new release.

**Comment by novabyte** [comment]
Thanks @lugehorsam 🙇
