### ISSUE TITLE
[Feature Request] Add file structure for Unreal client guide

### ISSUE THREAD

**Issue by SnappierSoap318** [heroiclabs/nakama-docs#207]
Add a file structure to the unreal client guide so that new users will know where to write the client side code. 

from my expirence, i wrote all the code( authentication, add to matchmaking, and joinmatch) in the game instance class as i need the session to persist across levels.

**Comment by seanpackham** [comment]
Hi, structuring your game is out of the scope of using Nakama's features. I can recommend looking at some Unreal specific guides for organizing/structuring your game and code.
