### ISSUE TITLE
Incorrect documentation on return types for the authenticate_token_generate method

### ISSUE THREAD

**Issue by zJudGenie** [heroiclabs/nakama-docs#221]
I think there is a copy-paste error as the [authenticate_token_generate](https://github.com/heroiclabs/nakama/blob/f1000c9308e7b1b67f164fc19ec118476b38a054/server/runtime_lua_nakama.go#L1666) Lua method returns the [`token` and the `expiry` ](https://github.com/heroiclabs/nakama/blob/f1000c9308e7b1b67f164fc19ec118476b38a054/server/runtime_lua_nakama.go#L1723) and not the user's ID, the username and a boolean flag indicating if the account was just created

https://heroiclabs.com/docs/nakama/server-framework/function-reference/#authenticate
https://github.com/heroiclabs/nakama-docs/blob/master/docs/nakama/server-framework/function-reference.md#authenticate

**Comment by gpene** [comment]
Thank you @zJudGenie 🙏  - we've made the fix and docs should be updated soon.
