### ISSUE TITLE
Rollup: CommonJS plugin throws SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by minosvasilias** [heroiclabs/nakama-docs#224]
I'm trying to get rollup working with my typescript setup since i'd like to use a node module (jsonwebtokens) for a custom authentication system. I followed the instructions in the docs, but when i run `npm run build`, i get the following error:

```
./src/main.ts → index.js...
[!] (plugin commonjs) SyntaxError: Unexpected token (1:14) in PROJECT_PATH\src\main.ts
src\main.ts (1:14)
1: let InitModule: nkruntime.InitModule = function (
                 ^
2:   ctx: nkruntime.Context,
3:   logger: nkruntime.Logger,
SyntaxError: Unexpected token (1:14) in PROJECT_PATH\src\main.ts
```
Presumably it expects JS, but is getting TS. Looking at `rollup.config.ts`, the plugins are ordered as described in the docs:

``` typescript
import resolve from "@rollup/plugin-node-resolve";
import commonJS from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import babel from "@rollup/plugin-babel";
import typescript from "@rollup/plugin-typescript";
import pkg from "./package.json";

const  extensions  = [".mjs",  ".js",  ".ts",  ".json"];

export  default  {
	input:  "./src/main.ts",
	external: ["nakama-runtime"],
	plugins: [
		// Allows node_modules resolution
		resolve({  extensions  }),
		// Compile TypeScript
		typescript(),
		json(),
		// Resolve CommonJS modules
		commonJS({  extensions  }),
		// Transpile to ES5
		babel({
			extensions,
			babelHelpers:  "bundled",
		}),
	],
	output:  {
		file:  pkg.main,
	},
};
```
So typescript compilation should be happening before we get to commonJS. My `tsconfig.json` looks exactly like the one described in the docs as well.
I'm at a bit of a loss, perhaps i am misunderstanding something about the process here. 
I tried setting `include:  "**/*.js"` as an option for commonJS, which does skip the commonJS error, but then just moves to Babel complaining about the same thing. As you'd expect i suppose. Am i right in thinking that the issue lies with the rollup typescript plugin not doing its job here? How could i get this working? Any help would be appreciated! 

Also, while the error is the same as in #214 , for me it appears specifically at the `commonJS` step, not the `resolve` step, and my project path seems to not be the issue.

**Comment by tomglenn** [comment]
Hi @minosvasilias.

Can you ensure the correct `include` path is set in `tsconfig.json`.

From the looks of it you should have it set to `"src/**/*"` and not `"**/*.js"`.

**Comment by minosvasilias** [comment]
Hey @tomglenn, thanks.
However my tsconfig `include` is set to `"src/**/*"` as you say.

**Comment by tomglenn** [comment]
@minosvasilias Thanks for that. The configuration files look correct. I've created a fresh and bare-bones TypeScript project repository, could you take a look and compare your existing project in terms of structure and content of the `main.ts` file.

https://github.com/tomglenn/nakama-typescript-project

**Comment by minosvasilias** [comment]
@tomglenn Thank you, very helpful. 

First off, just running your project worked without problems. 

Comparing with my own i did not notice any relevant differences apart from multiple other `.ts` files in my `src` folder. As a sanity check however i just overwrote my`src` folder with the one from your project, which resulted in a successful `npm run build`. 
I then one-by-one re-added my other `.ts` scripts as well as reverted to the contents of my original `main.ts` and... it still worked. 

So it took me a bit to notice, but it seems like the kicker was my `Main.ts` file **not being lowercase**. Renaming `main.ts` to `Main.ts` will immediately result in the same error again. And looking at the original error i posted, the commonjs plugin was also looking for a `main.ts` file.

Sadly, while it is compiling now, i'm facing another problem as it only appears to be compiling the contents of `main.ts`, not any of the other files.
For simple reproduction, i tried adding the following file to `src` in your repo:

`test.js`
```typescript
const TEST_CONSTANT = "TEST";

function testRPC(
	context: nkruntime.Context,
	logger: nkruntime.Logger,
	nk: nkruntime.Nakama,
	payload: string
): string {
	logger.info("Test print.");
	return TEST_CONSTANT;
}

```
and modified `main.ts`:

```typescript
let InitModule: nkruntime.InitModule = function (ctx, logger, nk, initializer) {
	logger.info("TypeScript module loaded.");
	initializer.registerRpc("test_rpc", testRPC);
};

!InitModule && InitModule.bind(null);
```


Yet the generated `index.js` looks like this:

```javascript
var InitModule = function InitModule(ctx, logger, nk, initializer) {
  logger.info("TypeScript module loaded.");
  initializer.registerRpc("test_rpc", testRPC);
};

!InitModule && InitModule.bind(null);
```

**Comment by tomglenn** [comment]
@minosvasilias Yes as you mentioned, you'll need to use `export` and `import` statements. (Rollup will discard unused code and since you weren't `import`ing your `testRPC` function the contents of `test.js` will have been discarded.)

Glad you got this issue resolved. I'll admit I would have never considered filename case sensitivity to be an issue! :)

**Comment by minosvasilias** [comment]
Yeah, it took me a while, too. :)
Thanks for the help, appreciate it!

**Comment by kunal2619** [comment]
Hey, I have the same setup as mentioned above. I have been trying to bundle all the `.ts` files. The `npm run build` command works successfully for me but it does not include any other `.ts` files other than the main.ts file in the output. Everything works well when I merge all `ts` files contents in the `main` file, but otherwise, the other files are just ignored. 

My project directory and `InitModule` looks like this,

```
let InitModule: nkruntime.InitModule =
    function(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, initializer: nkruntime.Initializer) {

        //Hooks
        initializer.registerAfterAuthenticateDevice(afterAuthenticateDeviceFn);

        initializer.registerMatchmakerMatched(matchmakerMatched);

        //RPC Calls
        initializer.registerRpc('load_card_inventory', rpcLoadCardsInventory);
        initializer.registerRpc('update_selected_deck_index', rpcUpdateSelectedDeckIndex);
        initializer.registerRpc('load_battle_entity_data', rpcLoadBattleEntityData);
        initializer.registerRpc('try', rpcLoadBattleEntityDataOther)

        logger.info("Typescript Initialised!!");
}
```

<img width="230" alt="Screenshot 2021-09-08 at 8 40 22 PM" src="https://user-images.githubusercontent.com/6876467/132536167-817052e2-9a6e-4bc5-afba-a00dfb374068.png">
