### ISSUE TITLE
Only one client connection

### ISSUE THREAD

**Issue by vladyslavshcherbaiev** [heroiclabs/nakama-docs#226]
Hi. 
It is necessary to block the possibility of multiple connections at one time using the same login details.
I have found the issue(https://github.com/heroiclabs/nakama/issues/42) but not a solution how to do it. 
Thanks.

**Comment by novabyte** [comment]
Hi @vladyslavshcherbaiev 👋 

Sorry your question is not clear what do you mean by "is it necessary to block [...] multiple connections". It is not necessary to do any restrictions on the number of open sockets an individual user can have with the server. Is your question actually: How do I limit the number of concurrent sessions by a single user to one?

**Comment by vladyslavshcherbaiev** [comment]
Hi @novabyte, your version of the question sounds more correct:) There is a task. User connects from device1, then using the same credentials connects from the second device. At the device1, session closes and app shows some message. At the device2, the user continues to work with app. Are there any options to do this. THX.

**Comment by gpene** [comment]
Hi @vladyslavshcherbaiev - You can use the `single_socket` configuration parameter to limit users to one session: https://heroiclabs.com/docs/nakama/getting-started/configuration/#session
