### ISSUE TITLE
Docs typo 

### ISSUE THREAD

**Issue by eleanorjmorel** [heroiclabs/nakama-docs#234]
the js sdk says there are two variables called token and refresh_token
![image](https://user-images.githubusercontent.com/32940085/151679149-1922987f-2f44-4c97-a229-48726523e904.png)

 but the documentation calls them something else: 
![image](https://user-images.githubusercontent.com/32940085/151679167-d9d328e1-565b-434c-b2a7-c8d7ea37a383.png)
 documentation source: https://heroiclabs.com/docs/nakama/client-libraries/javascript-client-guide/#session-lifecycle

**Comment by seanpackham** [comment]
Thank you for reporting @eleanorjmorel
