### ISSUE TITLE
RUDP Documentation Update

### ISSUE THREAD

**Issue by alexpareto** [heroiclabs/nakama-docs#48]
I think (but this is just from reading the PRs) there are only a couple of things to be documented and that's the addition of an optional `bool reliable` to the `Send` method:

```c#
void Send<T>(INCollatedMessage<T> message, Action<T> callback, Action<INError> errback);

void Send(INUncollatedMessage message, bool reliable, Action<bool> callback, Action<INError> errback);

void Send(INUncollatedMessage message, Action<bool> callback, Action<INError> errback);
```

and also the builder function with an extra type for client:
```c#
        _client = new NClient
            .Builder("defaultkey", TransportType.Udp)
            .Host("localhost")
            .Port(7350)
            .SSL(false)
            .Build();
```

One thing I'm not sure about - In the [blog post](https://blog.heroiclabs.com/nakama-1-2-released-udp-advanced-matchmaker-and-javascript-d9e9e46b6bd) it discusses RUDP versus Websocket. Is creating a client with the TransportType.Udp creating an RUDP client connection?

Referencing [this commit](https://github.com/heroiclabs/nakama-unity/commit/74a9902da562df5158770e738cf954bf34f0f99f#diff-4ac32a78649ca5bdd8e0ba38b7006a1e).

**Comment by mofirouz** [comment]
Hey @alexpareto - Yes that's right, that's how you tell the Unity Client to establish a rUDP connection with Nakama server. You'll also need to make sure that you pass [`socket.publish_address`](https://github.com/heroiclabs/nakama/blob/master/server/config.go#L248) to Nakama which is the direct publicly accessible IP address of that instance. 

We need to have general documentation on rUDP anyways to explain all this, why it is needed and what to do for servers behind firewalls or loadbalancers (if anything can be done depending on infrastructure configurations).

**Comment by mofirouz** [comment]
Closing this as this is currently irrelevant and new rUDP implementation will be different.
