### ISSUE TITLE
Paths typo in error

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama-docs#49]
https://heroiclabs.com/docs/storage-collections/#paths notice that INError is "error" whereas the logs are using "err"

`}, (INError error) => {
  Debug.LogErrorFormat("Error: code '{0}' with '{1}'.", err.Code, err.Message);`

**Comment by novabyte** [comment]
Thanks @ArisTsevrenis. Fixed in 35b4c9d92172b85322c93c21349428dbaef7820e.
