### ISSUE TITLE
missing limit options on the StorageListRequest

### ISSUE THREAD

**Issue by mickeyren** [heroiclabs/nakama-docs#54]
by default the StorageListRequest defaults to fetching only 10 at a time.

You can increase this to 100 by increasing the limit in the message like so `message.limit = 100` but the documentation doesn't cover this - https://heroiclabs.com/docs/storage-collections/#list-records

**Comment by novabyte** [comment]
The methods for the clients have changed since this issue was opened but I've added some clarity to the code examples. Fixed in c06e4bb14970027c2acc5512407f6c8481c0d1b6.
