### ISSUE TITLE
Javascript examples

### ISSUE THREAD

**Issue by pgregory** [heroiclabs/nakama-docs#55]
In the Fetch Self section, https://heroiclabs.com/docs/user-accounts/#fetch-self, the Javascript example looks like...

    var message = new nakamajs.SelfFetchRequest();
    client.send(message).then(function(result) {
        console.log("User id '%o' and handle '%o'.", result.self.id, result.self.handle);
        console.log("User has JSON metadata: %o", result.self.metadata);
    }).catch(function(error){
        console.log("An error occured: %o", error);
    })

The response is formatted differently to the expectations here, instead of `result.self.id` it should be `result.self.user.id` and similar for the other fields.

**Comment by mofirouz** [comment]
This is now fixed in 908a282.
