### ISSUE TITLE
Javascript examples

### ISSUE THREAD

**Issue by pgregory** [heroiclabs/nakama-docs#56]
In the "Link or unlink" section, https://heroiclabs.com/docs/authentication/#link-or-unlink, the code is as follows:

    var id = "062b0916-7196-11e7-8371-9fcee9f0b20c";
    
    var message = new nakamajs.LinkRequest()
    message.device = id;
    client.send(session).then (function(session){
        console.log("Successfully linked device ID to current user.");
    }).catch(function(error) {
        console.log("An error occured: %o", error);
    });

The call to `send` should take `message` as it's argument, not `session`.

**Comment by mofirouz** [comment]
This is now fixed in 908a282.
