### ISSUE TITLE
Link to production settings deployment guide on Homepage not working.

### ISSUE THREAD

**Issue by BernhardRubow** [heroiclabs/nakama-docs#57]
The link to the production settings deployment guide:

https://heroiclabs.com/docs/install-configuration/deployment-production-settings.md

returns a 404.

Found on https://heroiclabs.com/docs/install-configuration/

**Comment by novabyte** [comment]
@BernhardRubow Thanks. We'll add it to the next docs sprint. In the meantime for production deployments we recommend the following setup:

- Use whichever cloud provider you prefer. We recommend Google Cloud Platform.
- Have a look at the [configuration settings](https://heroiclabs.com/docs/install-configuration/) for the server. You'll need to set your own `--socket.server_key`, `--session.encryption_key`, and `--runtime.http_key` as a minimum with your server start command. This can be configured as part of a YAML configuration file or as command line flags.
- Setup a load balancer with SSL termination. All your app clients will connect to this address ideally with a DNS record for the host.
- Configure the load balancer to have it forward traffic to compute instances which run Nakama server.
- Setup compute instance(s) to run your database server and configure the IP and firewall so it's reachable by Nakama server. Pass the connection settings to Nakama server as command line flags or in the configuration YAML file.
- Test your app clients can connect and authenticate, etc.

Someone in the community has outlined these steps in a blog post:

http://www.stevestreeting.com/2018/03/21/setting-up-a-game-server-using-nakama-on-google-compute-engine-part-2/

Hope it helps. Let me know what feedback you have.

**Comment by seanpackham** [comment]
Broken link is no longer present.
