### ISSUE TITLE
Correct syntax for Update operation "remove"

### ISSUE THREAD

**Issue by nikitaosyak** [heroiclabs/nakama-docs#59]
[Current](https://heroiclabs.com/docs/storage-collections/#paths) storage collection docs are misleading, since it tells to separate array index with dot ``` "field.0" ```, but "remove" op syntax requires slashes ``` "/field/0" ```

**Comment by mofirouz** [comment]
Closing this as this is currently irrelevant and we don't have Storage Update in Nakama 2.
