### ISSUE TITLE
create_tournament example is incorrect

### ISSUE THREAD

**Issue by casperkl** [heroiclabs/nakama-docs#77]
The example found at:
https://heroiclabs.com/docs/gameplay-tournaments/#create-tournament

Does not match the definition found at:
https://heroiclabs.com/docs/runtime-code-function-reference/#tournaments

Another issue: the sort order var is called "sort" but in the call "sortOrder" is used.

**Comment by novabyte** [comment]
Thanks @casperkl. Nice catch we'll update the docs

**Comment by novabyte** [comment]
Fixed on 617e833d7e837e3455cea96a52ac95b4d1cde1a5.
