### ISSUE TITLE
MMO Style Stream API DOC/Example

### ISSUE THREAD

**Issue by juleswimmer** [heroiclabs/nakama-docs#78]
The docs about the stream api do not include example how to manage named streams to make some kind of mmorpg game. Maybe its possible ti improve those docs in general and include a full implementation example.

Thanks for your great work

**Comment by seanpackham** [comment]
Streams have labels which can be used to identify them https://heroiclabs.com/docs/nakama/server-framework/streams/#structure-of-a-stream
