### ISSUE TITLE
Windows Docker Path and Modules Directory Fix 

### ISSUE THREAD

**Issue by bigmoni** [heroiclabs/nakama-docs#79]
Problem: On Windows Docker nakama cant access folder if there is "//" https://heroiclabs.com/docs/install-docker-quickstart/#data

```
On Windows, you'll need to update the path above so that Docker can bind the folder properly. A valid value can look like this:

//c/Users/<username>/projects/docker:/nakama/data.
```

Fix:
`/c/Users/<username>/projects/docker:/nakama/data.`

Second Prolem:
`You can put your Lua scripts in the data/modules directory and restart Nakama using docker-compose --restart.`

Fix:
`You can put your Lua scripts in the /modules directory and restart Nakama using docker-compose --restart.`

**Comment by mofirouz** [comment]
Awesome - thanks so much. Fixed in f2d0bfdf4d3c7f5cfee2072e38daf2f00fb91ca1
