### ISSUE TITLE
No heroku deployment in docs

### ISSUE THREAD

**Issue by Codeavr** [heroiclabs/nakama-docs#80]
Official repository's "Deployment" section says (https://github.com/heroiclabs/nakama#deployment) that you can deploy nakama server on heroku, but there is no guide in the docs

**Comment by alisaffari97** [comment]
Really how we can deploy it on Heroku?!

**Comment by antv199** [comment]
got me curious as well

**Comment by DreadKnight** [comment]
I'm wondering about this as well. Heroku provides SSL, which I'm struggling to get right while hosting on DigitalOcean atm.

**Comment by novabyte** [comment]
@DreadKnight You want to move to Heroku from DigitalOcean? It's been quite a while since we had scripts which worked as a Heroku buildpack. I can look into what this will take but it used to be quite awkward because you couldn't easily convince Heroku to run code that comes already compiled. 🤔

**Comment by DreadKnight** [comment]
@novabyte Ideally would have wanted that DigitalOcean Nakama 1-click app from the marketplace to not be ancient and broken and to easily work with a SSL :D lost days getting the hang of ssh/docker and now I don't quite get why my SSL is not working.

**Comment by novabyte** [comment]
@DreadKnight Yep I think you've mentioned this multiple times. I understand that the Digital Ocean set up is outdated and needs improvement. It's also open-source on GitHub and we welcome all contributions:

https://github.com/heroiclabs/nakama/tree/master/build/do-marketplace

This thread is about Heroku and not about Digital Ocean. I will open a separate issue to cover updates to the free DO set up.

**Comment by seanpackham** [comment]
We no longer mention Heroku in the deployment section but Heroku support Docker deployments and their are unofficial buildpacks for Nakama out there. At this time we don't have plans to add official Heroku deployment guides.
