### ISSUE TITLE
md5_hash documentation missing

### ISSUE THREAD

**Issue by zaniar** [heroiclabs/nakama-docs#81]
When I look up the documentation for md5, I found nothing. So I try to search for other solution. Then I found that there is `md5_hash` exist in the source code (https://github.com/heroiclabs/nakama/blob/master/server/runtime_lua_nakama.go#L137).

There is possibility that some more others documentation missing.

**Comment by novabyte** [comment]
Fixed in 998bd52fb883b9000063907b243d57253034df86.
