### ISSUE TITLE
List users missing

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama-docs#9]
`
    public void ListGroupUsers( byte[] groupId )
    {
        NGroupUsersListMessage message = NGroupUsersListMessage.Default( groupId );

        m_Client.Send( message,
            ( INResultSet<INGroupUser> results ) =>
            {
                for( int i = 0; i < results.Results.Count; i++ )
                {
                    INGroupUser nakamaGroup = results.Results[ i ];
                    Debug.LogFormat( "User ID: '{0}'", nakamaGroup.Id );
                }
            },
            ( INError error ) =>
            {
                Debug.LogErrorFormat( "Could not find users in group: '{0}'.", error.Message );
            } );
    }`

**Comment by mofirouz** [comment]
This is added to master. Thanks for this :)
